name: Node Demo

on:
  push:
    branches:
      - dev

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check Node Version
        run: node -v

      - name: Check NPM Version
        run: npm -v

      - name: Print Current Directory
        run: pwd

      - name: List Files
        run: ls -la
